### ISSUE TITLE
UnauthorizedAccessException

### ISSUE THREAD

**Issue by jamd315** [AdmiralCurtiss/WfcPatcher#3]
wfcpatcher.exe "Pokemon Black.nds" > output

Reading and copying Pokemon Black.nds...
Failed patching Pokemon Black.nds
System.UnauthorizedAccessException: Access to the path 'C:\Users\Owner\Desktop\Pokemon Black.nds' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at WfcPatcher.Program.PatchFile(String filename, String newFilename)
   at WfcPatcher.Program.Main(String[] args)

I really hope this isn't me just being stupid, but that's the most likely cause.  Output from a command prompt with elevated privileges, Windows 7

**Comment by AdmiralCurtiss** [comment]
This just looks like some sort of access rights issue. Right-click the *.nds file -> Properties and make sure it's not read-only and your Windows account has full access in the "Security" tab.
